#!/usr/bin/env python3
"""Classify each orphan file as LIVE (imported by active code) or DEAD-CANDIDATE.

For each orphan, search the active codebase (excluding QUARANTINE/, the file
itself, and tests/) for any `import <module>` or `from <module> import` line.
"""
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

ORPHANS = [
    "ability_engine",
    "backfill_embeddings",
    "card_renderer",
    "codex_intents",
    "conftest",
    "embed_helpers",
    "espn_asset_scraper",
    "flow_audit",
    "flow_events",
    "flow_cards",
    "google_docs_writer",
    "ledger_poster",
    "oracle_agent",
    "oracle_analysis",
    "oracle_query_builder",
    "oracle_renderer",
    "pagination_view",
    "stress_test_ai",
    "stress_test_codex",
    "stress_test_history",
    "stress_test_vet",
    "test_all_renders",
    "test_oracle_stress",
    "test_prediction_v6",
    "test_query_builder",
    "upload_emoji",
]


def find_py_files():
    """All .py files in the repo, excluding QUARANTINE/, audits/, __pycache__/, .git/."""
    excluded_dirs = {"QUARANTINE", "audits", "__pycache__", ".git", "node_modules", "echo"}
    files = []
    for root, dirs, names in os.walk(REPO_ROOT):
        # Filter dirs in-place to prune the walk
        dirs[:] = [d for d in dirs if d not in excluded_dirs and not d.startswith(".")]
        for n in names:
            if n.endswith(".py"):
                files.append(Path(root) / n)
    return files


def find_importers(module_name, all_py_files):
    """Return list of files (relative to repo root) that import `module_name`.

    Skips the orphan file itself.
    """
    importers = []
    pattern = re.compile(
        rf"^\s*(?:from\s+{re.escape(module_name)}(?:\.[\w.]+)?\s+import|import\s+{re.escape(module_name)}(?:\s|$|,))",
        re.MULTILINE,
    )
    self_path_basename = f"{module_name}.py"
    for f in all_py_files:
        if f.name == self_path_basename:
            continue
        try:
            content = f.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        if pattern.search(content):
            importers.append(str(f.relative_to(REPO_ROOT)).replace("\\", "/"))
    return importers


def main():
    all_py = find_py_files()
    print(f"Scanning {len(all_py)} .py files in active codebase\n")

    print("# Orphan Classification\n")
    print("Generated by audits/spiral/_classify_orphans.py\n")
    print("Active codebase = all .py files NOT under QUARANTINE/, audits/, __pycache__/, .git/, echo/, or hidden directories.\n")
    print("| File | Importers (count) | Importer files | Classification |")
    print("|------|-------------------|----------------|----------------|")

    classifications = {}
    for orphan in ORPHANS:
        importers = find_importers(orphan, all_py)
        n = len(importers)
        if importers:
            classification = "LIVE"
            files_str = ", ".join(importers[:6]) + (" ...+more" if n > 6 else "")
        else:
            classification = "DEAD-CANDIDATE"
            files_str = "_(none)_"
        classifications[orphan] = (classification, importers)
        print(f"| `{orphan}.py` | {n} | {files_str} | **{classification}** |")

    # Summary
    live_count = sum(1 for c, _ in classifications.values() if c == "LIVE")
    dead_count = sum(1 for c, _ in classifications.values() if c == "DEAD-CANDIDATE")
    print(f"\n## Summary\n")
    print(f"- LIVE (importers found in active code): **{live_count}**")
    print(f"- DEAD-CANDIDATE (no importers in active code): **{dead_count}**")

    # Recommendation section
    print(f"\n## DEAD-CANDIDATE files (recommend QUARANTINE move)\n")
    for orphan, (cls, imp) in classifications.items():
        if cls == "DEAD-CANDIDATE":
            print(f"- `{orphan}.py`")

    print(f"\n## LIVE files (Argus's static scan missed an import path)\n")
    for orphan, (cls, imp) in classifications.items():
        if cls == "LIVE":
            print(f"- `{orphan}.py` ← imported by: {', '.join(imp)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
